### PR TITLE
update frontend

### PR DESCRIPTION
**Pull request by aviran6709**

### CODE REVIEW

**Comment by aviran6709** [comment]
add pull

**Comment by FiLLa-FaS** [comment]
Hi! Thank you for sending your project for review, great job! I like responsive layout and matching with the mockup, js functionality works correctly. I left several issues below, you need to fix them to pass the sprint. Good luck with refactoring!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * Incorrect text properties of `card__date`
    * Take a look at `navigation__links_tittle_save-article_dark` bottom border (please check its width and location)
    * Incorrect text properties of `navigation__links_tittle_save-article_dark`
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * Incorrect location of `news-results__tittle` on 768 viewport
    * Incorrect height of the `card` on 768, 320 viewport
    * Incorrect distance between `about__title` and `about__text` on 768, 320 viewport
    * Please check all spaces inside `header` on 768 viewport
    * Incorrect width of `card__title` and `card__text` on 320 viewport
    * `popup__close-btn` shouldn't extend outside the screen on intermediate screen resolutions
    * `navigation_menu` is displayed incorrectly on 741px+ screen resolutions (and please note, that this element shouldn't be opened when we open popup
    * Incorrect spaces between elements inside `header` on 768 viewport
    * Incorrect distance between `navigation` and `save-news` on 768 viewport
    * Incorrect word wrap in `save-news__subtitle` on 320 viewport
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
    * Links inside footer are not active (github and facebook icons should be interactive links)
- [x]  Classes are named according to BEM specifications.
    * Modifiers shouldn't be used without base class (please fix all similar cases throughout the project)
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Please use `header`, `footer`, `main`, `section` tags instead of `div` where necessary
    * `search-form__search-bar` should be a form
    * Please use list tags for `card-list`
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Note, that most of interactive elements should have at least 2 states in UI kit (and cursor should be changed to pointer for all interactive elements)
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
    * Not all icons are used in `svg` format
- [x]  Form elements should be highlighted when focused.
    * Popup sign up/sign in switcher is not focused
- [x]  The form must have placeholders,  and there are required properties for the fields.
    * `search-from__input` doesn't have a placeholder
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
    * Not all fonts have fallback or generic families in styles
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 43

**Comment by FiLLa-FaS** [comment]
Hey! Good job, your project looks much better now! But there're still several issues, please fix them to pass the stage. Good luck!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
    * You need to fix `font-family` rule throughout the project, now fonts are not displayed correctly on the page (each font should be wrapped with quotation marks except generic family, not all values with only one pair of quotation marks)
    * Incorrect location of `card-list` (you need to reset default left padding of the `ul` tag
- [ ]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page scrolls horizontally on 1201px - 1288px screen resolutions on both pages and on 320px - 352px screen resolutions on `saved-news` page
    * Incorrect distance between `about__title` and `about__text` on 768, 320 viewport
    * Please check all spaces between elements inside `header` section on 768 viewport on both pages
    * `popup__close-btn` shouldn't extend outside the screen on intermediate screen resolutions http://joxi.ru/v29bD6Xc4vW4dA
    * Incorrect width of `save-news` on 768 viewport http://joxi.ru/Q2Kk4NLfO1ROR2
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Modifiers shouldn't be used without base class (please fix all similar cases throughout the project)
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Please move `header` and `footer` sections outside the `main` tag
    * Empty `div` without the class should be removed, it's redundant http://joxi.ru/nAylQ4bT9L5kZ2
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [ ]  Buttons, input fields, and links are implemented in all of the states specified in the design.
    * Note, several elements also should have active state, all necessary states are described in the UI kit http://joxi.ru/krDa4XjHGl6LXm (and sign up/ sign in switcher should have changed the cursor when the cursor is on the element http://joxi.ru/nAylQ4bT9L5GZ2
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [ ]  The icons are exported in SVG format.
    * All icons should be in svg format http://joxi.ru/l2ZzMOlTl13kx2
- [x]  Form elements should be highlighted when focused.
    * Popup sign up/sign in switcher is not focused http://joxi.ru/eAO8MQRcvzbEYr
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [x]  System fonts are connected as alternatives to each of your fonts.
    * Not all fonts have fallback or generic families in styles
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 58

**Comment by FiLLa-FaS** [comment]
Hey! Your project is almost finished, you should get only 3 more scores to pass this stage. Good luck with the refactoring!

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
    * The page scrolls horizontally on 1233px - 1248px screen resolutions
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [ ]  Classes are named according to BEM specifications.
    * Modifiers shouldn't be used without base class (you can see the example on the screenshot http://joxi.ru/brRqjWQhBWWjJA. Please fix all similar cases throughout the project)
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
    * Empty `div` without the class should be removed, it's redundant http://joxi.ru/nAylQ4bT9L5kZ2
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
    * Not all fonts have fallback or generic families in styles (please check all the project and set generic family or fallback font for all `font-family` styles)
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 77

**Comment by FiLLa-FaS** [comment]
Hey! Almost all issues are fixed, so your project has been accepted! Good luck with the next diploma stage

# Summary:
### Performance Criteria

- [x]  All the blocks from the brief have been coded. The layout matches the designs for all resolutions from the mockup. Differences in size should not visually contradict the layout and get out of the grid in the layout.
- [x]  The project is adapted for different screen resolutions and looks correctly on all intermediate resolutions.  There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an empty anchor on the page and external links open in a new tab. All project pages can be accessed, and hidden blocks can be displayed.
- [x]  Classes are named according to BEM specifications.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of `<div />` containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  `flex` or `grid`  layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
  - [x]  The markup is included within parentheses `( )`.
  - [x]  The markup has been moved into the corresponding components.
- [x]  Your project contains:
  - [x] An `images`
  - [x] A `components` folder with JS and CSS files for the components.
  - [x] A `fonts` folder.
- [x]  There are no linting errors or warnings.

### Best Practices

- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using `@font-face`.
- [x]  The icons are exported in SVG format.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders,  and there are required properties for the fields.
- [x]  The use of `reset.css` is prohibited.


### Recommendations

- [ ]  System fonts are connected as alternatives to each of your fonts.
- [x]  Images have an `alt` attribute containing appropriate values.
- [x]  Raster and vector images have been optimized.

## Number of points: 98

**Pull request merged**
